collections:
   #- name: ansible.tower
   #- name: awx.awx
   #- name: nginxinc.nginx_core
   - name: deekayen.cleanmgr
     source: https://galaxy.ansible.com
   #- name: community.kubernetes
   #- src: https://github.com/deekayen/ansible-role-cleanmgr
     #version: master
     #name: ansible-role-cleanmgr
