---
# Ansible playbook to install chocolatey packages

- name: Install multiple packages
  hosts: all
  gather_facts: true
  tasks:
    - name: Install procexp
      win_chocolatey:
          name: 
          - procexp
          #- putty
          #- windirstat
          state: present
    - name: Install putty
      win_chocolatey:
          name: 
          #- procexp
          - putty
          #- windirstat
          state: present
    - name: Install windirstat
      win_chocolatey:
          name: 
          #- procexp
          #- putty
          - windirstat
          state: present

          
