---
# Ansible playbook to run Windows Update and restart, if required
#
# http://docs.ansible.com/ansible/win_updates_module.html
# https://docs.ansible.com/ansible/win_reboot_module.html

- name: Install all security, critical, and rollup updates without a scheduled task
  hosts: all
  gather_facts: true
  tasks:
    win_updates:
      category_names:
        - SecurityUpdates
        - CriticalUpdates
        - UpdateRollup
      state: searched
      log_path: C:\ansible_wu.tx
      register: result

    # output results
    #- debug: var=result

    # reboot only if required
    #- win_reboot:
     # when: result.reboot_required
