---
# Ansible playbook to run Windows Update and restart, if required
#
# http://docs.ansible.com/ansible/win_updates_module.html
# https://docs.ansible.com/ansible/win_reboot_module.html

- name: Install all security, critical, and rollup updates without a scheduled task
  hosts: all
  gather_facts: true
  tasks:
    - name: Search for updates
      win_updates:
          #reboot_timeout: 1200 # not required. The time in seconds to wait until the host is back online from a reboot.,This is only used if C(reboot=True) and a reboot is required.
          log_path: C:\ansible_wu.log # not required. If set, C(win_updates) will append update progress to the specified file. The directory must already exist.
          #whitelist: undefined # not required. A list of update titles or KB numbers that can be used to specify which updates are to be searched or installed.,If an available update does not match one of the entries, then it is skipped and not installed.,Each entry can either be the KB article or Update title as a regex according to the PowerShell regex rules.,The whitelist is only validated on updates that were found based on I(category_names). It will not force the module to install an update if it was not in the category specified.
          category_names: # not required. choices: Application;Connectors;CriticalUpdates;DefinitionUpdates;DeveloperKits;FeaturePacks;Guidance;SecurityUpdates;ServicePacks;Tools;UpdateRollups;Updates. A scalar or list of categories to install updates from
            - SecurityUpdates
            - CriticalUpdates
            - UpdateRollups
            - Updates
          
    # output results
    - debug: var=result

    # reboot only if required
    - win_reboot:
        #pre_reboot_delay: 2 # not required. Seconds for shutdown to wait before requesting reboot
        #post_reboot_delay: 0 # not required. Seconds to wait after the reboot was successful and the connection was re-established,This is useful if you want wait for something to settle despite your connection already working
        test_command: whoami # not required. Command to expect success for to determine the machine is ready for management
        #shutdown_timeout: 600 # not required. Maximum seconds to wait for shutdown to occur,Increase this timeout for very slow hardware, large update applications, etc,This option has been removed since Ansible 2.5 as the win_reboot behavior has changed
        reboot_timeout: 1800 # not required. Maximum seconds to wait for machine to re-appear on the network and respond to a test command,This timeout is evaluated separately for both network appearance and test command success (so maximum clock time is actually twice this value)
        msg: Reboot initiated by Ansible # not required. Message to display to users
        connect_timeout: 5 # not required. Maximum seconds to wait for a single successful TCP connection to the WinRM endpoint before trying again
      when: result.reboot_required
